## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
title = "Маршрути Київської Сотки"

## -----------------------------------------------
## Publish
## -----------------------------------------------

# relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  title = "Маршрути Київської Сотки"
  description = "Маршрути велоперегонів Київська Сотка від 2014 року до сьогодення"
  images = ["images/kc2018_with_2014_route.jpg"]
  logo = "images/kc_logo.png"
  favicon = true

[Params.social]
  github = "https://github.com/velosotka/velosotka.github.io"
  instagram = "https://instagram.com/oleksandr.red"
  linkedin = "https://linkedin.com/in/alexandear"
  email = "oleksandr.red+velosotka@gmail.com"
  telegram = "https://t.me/alexandear"
  strava = "https://www.strava.com/athletes/23735367"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputFormats]
  [outputFormats.gpsmap]
    mediaType = "text/html"
    baseName = "index"
    isPlainText = false
    notAlternative = true
    permalinkable = true

[outputs]
  home = ["HTML"]
  page = ["HTML", "gpsmap"]
